### ISSUE TITLE
Implement landing page in React (typescript)

### ISSUE THREAD

**Issue by edoomm** [rebo-it/prototypes#10]
Implement:
![Image](https://github.com/user-attachments/assets/a1041d86-46e6-4b36-ba24-1c328c50e068)

Acceptance criteria:
- [x] Use a framework
- [x] Use components
- [x] `Sign Up` button must redirect (blank page for part 2 with Typescript)
- [x] Must be responsive

**Comment by Therealsamumanz** [comment]
![image](https://github.com/user-attachments/assets/83a97b1f-e59e-412f-ba77-d9527dc0a460)
This is the General Diagram that will be implemented.
